### ISSUE TITLE
command file is kaput

### ISSUE THREAD

**Issue by OwOLolCat** [Silverfeelin/Starbound-Instrumentalizer#5]
For some odd reason, the instrumentalizer is refusing to give me a command file for this image no matter what I do.
![miditar](https://user-images.githubusercontent.com/105649243/183961686-be97716e-b6c2-404b-83bc-38254b2f01f9.png)
 the json works just fine, but I need a command file because I have no idea how the json works. Please fix this!
 
 edit: the command button is just broken entirely, I've tried everything, even using another image, fix the command button i beg you.

**Comment by Vortetty** [comment]
Closing as the command button has been fixed, if it is not fixed for you you can [clear your cache](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop) or just wait a few days

article is for chrome, use your browser to find articles on how to clear the cache for your current browser

**Comment by OwOLolCat** [comment]
this is still an issue for me, even after waiting forever and clearing my cache of everything it can cough up, are you 100% SURE you've done everything you can?
